baseURL = "https://chrilves.github.io/hugo"
#baseURL = ""
languageCode = "en-US"
defaultContentLanguage = "en"

title = "@chrilves' Archives"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

enableRobotsTXT = true
pygmentsCodefences = true
linenos = "table"
canonifyurls = true

publishDir = "../hugo"

[params]
  editURL = "https://github.com/chrilves/chrilves.github.io/edit/master/hugo/"
  description = "@chrilves' Archives"
  author = "@chrilves"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/chrilves"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/chrilves"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-linkedin'></i> LinkedIn"
identifier = "linkedin"
url = "https://www.linkedin.com/in/christophe-calv%C3%A8s-ab6325b0/"
weight = 10

#[Languages]
#[Languages.en]
#title = "@chrilves' Archives"
#weight = 1
#languageName = "English"
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-github'></i> Github"
#identifier = "ds"
#url = "https://github.com/chrilves"
#weight = 10
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
#identifier = "twitter"
#url = "https://twitter.com/chrilves"
#weight = 10
#
#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
#identifier = "twitter"
#url = "https://twitter.com/chrilves"
#weight = 10

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-camera'></i> Showcases"
#url = "showcase"
#weight = 11

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30

#[Languages.fr]
#title = "@chrilves' Archives"
#weight = 2
#languageName = "Français"

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-github'></i> Github"
#identifier = "ds"
#url = "https://github.com/chrilves"
#weight = 10

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
#identifier = "twitter"
#url = "https://twitter.com/chrilves"
#weight = 10

#[[Languages.en.menu.shortcuts]]
#name = "<i class='fab fa-fw fa-linkedin'></i> LinkedIn"
#identifier = "linkedin"
#url = "https://www.linkedin.com/in/christophe-calv%C3%A8s-ab6325b0/"
#weight = 10

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
#url = "/showcase"
#weight = 11

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[Languages.fr.menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
#url = "/credits"
#weight = 30
